[package]
name = "etherduck"
version = "0.1.0"
edition = "2024"
description = "Rust-based indexing tool that indexes EVM events"
repository = "https://github.com/bilinearlabs/etherduck"
homepage = "https://www.bilinearlabs.io"
readme = "README.md"
keywords = ["evm", "indexing", "events", "ethereum"]

[dependencies]

