[package]
name = "etherduck"
version = "0.1.0"
edition = "2024"
description = "Rust-based indexing tool that indexes EVM events"
repository = "https://github.com/bilinearlabs/etherduck"
homepage = "https://www.bilinearlabs.io"
readme = "README.md"
keywords = ["evm", "indexing", "events", "ethereum"]

[dependencies]
alloy = { version = "1.1.0", features = ["rpc-types", "json", "rpc-client", "json-rpc"] }
anyhow = "1.0.100"
clap = { version = "4.5.51", features = ["derive"] }
dashmap = "6.1.0"
duckdb = { version = "1.4.1", features = ["bundled"] }
secrecy = "0.10.3"
tokio = { version = "1.48.0", features = ["rt-multi-thread", "macros", "sync", "time", "tracing"]}
