name: Podman build & push

on:
  workflow_dispatch:
  push:
    tags:
      - 'v*'

jobs:
    build-push:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v4
            - name: Write release version
              run: |
                VERSION=${GITHUB_REF_NAME#v}
                echo Version: $VERSION
                echo "VERSION=$VERSION" >> $GITHUB_ENV
            - name: Use Podman Build and Push Action
              uses: Frozen-Tapestry/container-action@v1.4.0
              with:
                login_registry: ghcr.io
                login_username: ${{ github.actor }}
                login_password: ${{ secrets.REGISTRY_TOKEN }}
                dockerfile: ./Containerfile
                labels: io.containers.autoupdate=registry
                tags: ghcr.io/${{ github.repository }}:${{ env.VERSION }} ghcr.io/${{ github.repository }}:latest
                extra_args: --annotation org.opencontainers.image.authors=Felipe\ Torres\ Gonzalez<felipe@bilinearlabs.io> --annotation org.opencontainers.image.description=Etherduck\ Indexer
                push: true
                security: |
                  --security-opt=seccomp=unconfined
                  --security-opt=apparmor=unconfined
